In [ ]:
pip install tensorflow

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [ ]:
voc_size=10000

In [ ]:
onehot_repr=[one_hot(i,voc_size)for i in sent]
print(onehot_repr)

[[9492, 9895, 4042, 5078], [9492, 9895, 4042, 8494], [9492, 9444, 4042, 7193], [5207, 6684, 6677, 4414, 9633], [5207, 6684, 6677, 4414, 1133], [3796, 9492, 4195, 4042, 7512], [8393, 3004, 6640, 4414]]


In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
import numpy as np

In [ ]:
sent_length=8
embedded_doc=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_doc)

[[   0    0    0    0 9492 9895 4042 5078]
 [   0    0    0    0 9492 9895 4042 8494]
 [   0    0    0    0 9492 9444 4042 7193]
 [   0    0    0 5207 6684 6677 4414 9633]
 [   0    0    0 5207 6684 6677 4414 1133]
 [   0    0    0 3796 9492 4195 4042 7512]
 [   0    0    0    0 8393 3004 6640 4414]]


In [ ]:
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_doc))

[[[-0.02934184  0.03741021  0.02563796 -0.01303091  0.00109471
    0.0470291   0.01406932 -0.02951783 -0.04438085  0.01724659]
  [-0.02934184  0.03741021  0.02563796 -0.01303091  0.00109471
    0.0470291   0.01406932 -0.02951783 -0.04438085  0.01724659]
  [-0.02934184  0.03741021  0.02563796 -0.01303091  0.00109471
    0.0470291   0.01406932 -0.02951783 -0.04438085  0.01724659]
  [-0.02934184  0.03741021  0.02563796 -0.01303091  0.00109471
    0.0470291   0.01406932 -0.02951783 -0.04438085  0.01724659]
  [ 0.02549003 -0.02326655 -0.03098667  0.00321188  0.04437778
    0.02939859 -0.04190449  0.0008123   0.00168703 -0.02901104]
  [-0.01423901 -0.02601646 -0.0275831  -0.00780642 -0.04598116
    0.00884636  0.00812585 -0.03154957  0.02493724 -0.04993754]
  [-0.01976963  0.04556198 -0.00507583  0.04120487  0.0058881
   -0.03344064  0.03325137  0.00910543 -0.02668462 -0.00384157]
  [ 0.03952106  0.0348732  -0.04600262  0.02520202 -0.00741496
    0.03958805 -0.01579934  0.00017853  0.0382152

In [ ]:
print(model.predict(embedded_doc[0]))

[[[-0.02934184  0.03741021  0.02563796 -0.01303091  0.00109471
    0.0470291   0.01406932 -0.02951783 -0.04438085  0.01724659]]

 [[-0.02934184  0.03741021  0.02563796 -0.01303091  0.00109471
    0.0470291   0.01406932 -0.02951783 -0.04438085  0.01724659]]

 [[-0.02934184  0.03741021  0.02563796 -0.01303091  0.00109471
    0.0470291   0.01406932 -0.02951783 -0.04438085  0.01724659]]

 [[-0.02934184  0.03741021  0.02563796 -0.01303091  0.00109471
    0.0470291   0.01406932 -0.02951783 -0.04438085  0.01724659]]

 [[ 0.02549003 -0.02326655 -0.03098667  0.00321188  0.04437778
    0.02939859 -0.04190449  0.0008123   0.00168703 -0.02901104]]

 [[-0.01423901 -0.02601646 -0.0275831  -0.00780642 -0.04598116
    0.00884636  0.00812585 -0.03154957  0.02493724 -0.04993754]]

 [[-0.01976963  0.04556198 -0.00507583  0.04120487  0.0058881
   -0.03344064  0.03325137  0.00910543 -0.02668462 -0.00384157]]

 [[ 0.03952106  0.0348732  -0.04600262  0.02520202 -0.00741496
    0.03958805 -0.01579934  0.00017